services:

  _defaults:
    autoconfigure: true
    autowire: true

  Alpdesk\AlpdeskGoogleFonts\Controller\AlpdeskGoogleFontsController:
    arguments:
      - '@contao.csrf.token_manager'
      - '%contao.csrf_token_name%'
      - '@router'
      - '@security.helper'
      - '%kernel.project_dir%'
      - '@contao.framework'
      - '@request_stack'
    tags:
      - controller.service_arguments